substitutions:
  name: votronic-solar-charger
  device_description: "Monitor a Votronic Solar Charger via the display link port (UART)"
  external_components_source: github://syssi/esphome-votronic@main
  tx_pin: GPIO4
  rx_pin: GPIO5
  rx_timeout: 600ms

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-votronic"
    version: 3.1.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 1000
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

votronic:
  - id: votronic0
    uart_id: uart_0
    rx_timeout: ${rx_timeout}
    throttle: 2s

binary_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

    charger_charging:
      name: "${name} charger charging"
    charger_discharging:
      name: "${name} charger discharging"
    charger_controller_active:
      name: "${name} charger controller active"
    charger_current_reduction:
      name: "${name} charger current reduction"
    charger_aes_active:
      name: "${name} charger aes active"

    charging_converter_charging:
      name: "${name} charging converter charging"
    charging_converter_discharging:
      name: "${name} charging converter discharging"
    charging_converter_controller_active:
      name: "${name} charging converter controller active"
    charging_converter_current_reduction:
      name: "${name} charging converter current reduction"
    charging_converter_aes_active:
      name: "${name} charging converter aes active"

    pv_controller_active:
      name: "${name} pv controller active"
    pv_current_reduction:
      name: "${name} pv current reduction"
    pv_aes_active:
      name: "${name} pv aes active"

sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_voltage:
      name: "${name} battery voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    battery_status_bitmask:
      name: "${name} battery status bitmask"

    charger_current:
      name: "${name} charger current"
    charger_power:
      name: "${name} charger power"
    charger_load:
      name: "${name} charger load"
    charger_controller_temperature:
      name: "${name} charger controller temperature"
    charger_mode_setting_id:
      name: "${name} charger mode setting id"
    charger_battery_status_bitmask:
      name: "${name} charger battery status bitmask"
    charger_controller_status_bitmask:
      name: "${name} charger controller status bitmask"

    charging_converter_battery_voltage:
      name: "${name} charging converter battery voltage"
    charging_converter_secondary_battery_voltage:
      name: "${name} charging converter secondary battery voltage"
    charging_converter_current:
      name: "${name} charging converter current"
    charging_converter_power:
      name: "${name} charging converter power"
    charging_converter_load:
      name: "${name} charging converter load"
    charging_converter_controller_temperature:
      name: "${name} charging converter controller temperature"
    charging_converter_mode_setting_id:
      name: "${name} charging converter mode setting id"
    charging_converter_battery_status_bitmask:
      name: "${name} charging converter battery status bitmask"
    charging_converter_controller_status_bitmask:
      name: "${name} charging converter controller status bitmask"

    pv_controller_status_bitmask:
      name: "${name} pv controller status bitmask"
    pv_controller_temperature:
      name: "${name} pv controller temperature"
    pv_battery_status_bitmask:
      name: "${name} pv battery status bitmask"
    pv_voltage:
      name: "${name} pv voltage"
    pv_current:
      name: "${name} pv current"
    pv_power:
      name: "${name} pv power"

text_sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_status:
      name: "${name} battery status"

    charger_mode_setting:
      name: "${name} charger mode setting"
    charger_battery_status:
      name: "${name} charger battery status"
    charger_controller_status:
      name: "${name} charger controller status"

    charging_converter_mode_setting:
      name: "${name} charging converter mode setting"
    charging_converter_battery_status:
      name: "${name} charging converter battery status"
    charging_converter_controller_status:
      name: "${name} charging converter controller status"

    pv_mode_setting:
      name: "${name} pv mode setting"
    pv_controller_status:
      name: "${name} pv controller status"
    pv_battery_status:
      name: "${name} pv battery status"
