substitutions:
  name: votronic-solar-charger
  device_description: "Monitor a Votronic Solar Charger via the display link port (UART)"
  external_components_source: github://syssi/esphome-votronic@main
  tx_pin: GPIO4
  rx_pin: GPIO5
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-votronic"
    version: 3.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 1000
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

votronic:
  - id: votronic0
    uart_id: uart_0
    rx_timeout: ${rx_timeout}
    throttle: 2s

binary_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

    charger_charging:
      name: "${name} charger charging"
    charger_discharging:
      name: "${name} charger discharging"
    charger_controller_active:
      name: "${name} charger controller active"
    charger_current_reduction:
      name: "${name} charger current reduction"
    charger_aes_active:
      name: "${name} charger aes active"

sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_voltage:
      name: "${name} battery voltage"
    secondary_battery_voltage:
      name: "${name} secondary battery voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charger_load:
      name: "${name} charger load"
    charger_controller_temperature:
      name: "${name} charger controller temperature"
    charging_mode_setting_id:
      name: "${name} charging mode setting id"
    battery_status_bitmask:
      name: "${name} battery status bitmask"
    charger_controller_status_bitmask:
      name: "${name} charger controller status bitmask"

text_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging_mode_setting:
      name: "${name} charging mode setting"
    battery_status:
      name: "${name} battery status"
    charger_controller_status:
      name: "${name} charger controller status"
