substitutions:
  name: votronic-solar-charger
  device_description: "Monitor a Votronic Solar Charger via the display link port (UART)"
  external_components_source: github://syssi/esphome-votronic@main
  tx_pin: GPIO4
  rx_pin: GPIO5
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-votronic"
    version: 1.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

# If you use Home Assistant please remove this `mqtt` section and uncomment the native `api` component!
# api:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  - id: uart0
    baud_rate: 1000
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false

votronic:
  - id: votronic0
    uart_id: uart0
    update_interval: 2s
    rx_timeout: ${rx_timeout}
    enable_fake_traffic: false

binary_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_voltage:
      name: "${name} battery voltage"
    secondary_battery_voltage:
      name: "${name} secondary battery voltage"
    state_of_charge:
      name: "${name} state of charge"
    current:
      name: "${name} current"

    pv_voltage:
      name: "${name} pv voltage"
    pv_current:
      name: "${name} pv current"
    pv_power:
      name: "${name} pv power"
    battery_status_bitmask:
      name: "${name} battery status bitmask"
    charging_controller_status_bitmask:
      name: "${name} charging controller status bitmask"
    pv_controller_status_bitmask:
      name: "${name} pv controller status bitmask"
    charging_mode_setting_id:
      name: "${name} charging mode setting id"
    controller_temperature:
      name: "${name} controller temperature"

text_sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_status:
      name: "${name} battery status"
    charging_controller_status:
      name: "${name} charging controller status"
    pv_controller_status:
      name: "${name} pv controller status"
    charging_mode_setting:
      name: "${name} charging mode setting"
